### ISSUE TITLE
https://libreddit.bus-hit.me

### ISSUE THREAD

**Issue by avincent98144** [redlib-org/redlib-instances#67] opened 2024-09-28 18:03 UTC
### Country

USA

### Cloudflare enabled?

No

### What type of instance is it?

HTTPS

### URL

https://libreddit.bus-hit.me

**Comment by avincent98144** [comment] 2024-09-28 18:05
As of Sep 25, 2024 any time a video is clicked on to play, the entire primary site freezes for about 5 minutes. Tested nearly 30 times and every single time, freeze, no refresh activity and URL sits in address bar for about 5 minutes, then is OK. All is good - until clicking on a video to play. This started as of 9/25 across the board and across all reddit sites.

**Comment by avincent98144** [comment] 2024-09-28 18:06
Tried  on 5 different browsers [MacOS] and the same issue.

**Comment by sigaloid** [comment] 2024-09-28 18:18
I cannot reproduce on any devices on this instance. Is there any relevant error messages in the browser console?

**Comment by avincent98144** [comment] 2024-09-28 18:27
yup: [Error] Failed to load resource: You do not have permission to access the requested resource. Invoked every time a video hits play but not until then, the “first frame” of the vid loads.

**Comment by avincent98144** [comment] 2024-09-28 18:33
This is also new and may be related: If I download the vid [via DOWNIE or browser SAVE AS], Finder will show it as a GIF [when it natively is not a GIF, but inconsistently. I have to manually change the extension to .MP4 for it to play locally.

**Comment by sigaloid** [comment] 2024-09-28 18:52
Is this on every single video and redlib instance? Can you give a link to a video this is happening on?

Also - can you try turning on HLS in settings?

**Comment by avincent98144** [comment] 2024-09-28 18:56
a sample vid that this happens to all 10 times tested in the last 30m: https://libreddit.bus-hit.me/vid/jf9xdi50i7w41/720?source=fallback

**Comment by avincent98144** [comment] 2024-09-28 18:58
HLS does not reproduce the issue, vids play immediately. If this instance is behind Cloudflare, could that be the issue, given the entire instance is dead for that 5-6 minutes?

**Comment by avincent98144** [comment] 2024-09-28 19:01
OK .. now that instance is stalling every 7-8 minutes of 5-6 minutes each time for nearly an hour now. This is new. No other instance appears to be affected and no other web traffic is affected.

**Comment by avincent98144** [comment] 2024-09-29 21:27
how do I contact the host of this instance and tell him in the last week, the site freezes for about 2-3 minutes every 10 minutes or so?

**Comment by avincent98144** [comment] 2024-09-29 21:32
Now the instance site is freezing every 10 minutes or so for 2-3 minutes each time without any user actions. Yes, all other web sites work as expected.

**Comment by sigaloid** [comment] 2024-09-29 21:32
@austinhuang0131

**Comment by sigaloid** [comment] 2024-09-29 21:33
You can feel free to contact the owner at the relevant page on the site (https://bus-hit.me/#contact). But this isn't relevant to this repo, so closing for now

**Closed by sigaloid** 2024-09-29 21:33 UTC
